name: Testing Workflow

on:
  pull_request:
    branches:
      - develop

jobs:
  testing:
    name: Lint Check and Testing

    runs-on: ubuntu-latest

    steps:
      - name: Chekout Repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17.0.8
        uses: actions/setup-java@v1
        with:
          java-version: 17.0.8

      - name: Run Android Linter
        run: ./gradlew :sphinx:application:sphinx:lintDebug --warning-mode=all

      - name: Run Unit Tests
        run: ./gradlew :sphinx:application:sphinx:testDebugUnitTest

      - name: Assemble Debug APK
        run: ./gradlew :sphinx:application:sphinx:assembleDebug

      - name: Assemble Debug Test APK
        run: ./gradlew :sphinx:application:sphinx:assembleDebugAndroidTest
